spring.application.name=08_JPARepositoryDemo

spring.datasource.url=jdbc:mysql://localhost:3306/Product_Demo
spring.datasource.username=root
spring.datasource.password=vsk@2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true